on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  SDK_VER: v3.1.1
  SDK_VER_HEX: "0x03010100"
  NCS_ZIGBEE_VER: v1.2.1
  NCS_ZIGBEE_VER_HEX: "0x01020100"
  BOARD: nrf52840dk
  BOARD_TARGET: nrf52840dk/nrf52840
  BOARD_TARGET_NAME: nrf52840dk_nrf52840
  BAUDRATE: 115200

jobs:
  build-r23:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Clone the repo to a subdirectory, so we can initialize the Zephyr
          # workspace in the parent directory.
          path: zephyr-workspace/extra
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
           python-version: 3.13

      - name: 🧰 Install Dependencies + West
        # Install the Zephyr host build dependencies, and the `west` Python tool.
        # This list is from Zephyr's getting started guide:
        # https://docs.zephyrproject.org/latest/develop/getting_started/index.html
        run: |
          sudo apt update
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

          pip3 install west

      - name: 🪁 Install Zephyr SDK
        # Fetch the Zephyr SDK from the GitHub Release artifact, unpack it and
        # run the setup script, selecting the '-c' option to install cmake
        # packages and the '-t arm-zephyr-eabi' option to install the toolchain
        # only for the arm-zephyr-eabi (Cortex-M) architecture, since we don't
        # need the other toolchains (xtensa, riscv, etc.)
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.9/zephyr-sdk-0.16.9_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.9_linux-x86_64_minimal.tar.xz -C ~/
          ~/zephyr-sdk-0.16.9/setup.sh -c -t arm-zephyr-eabi

      # git clone https://github.com/nrfconnect/sdk-nrf.git zephyr-workspace/nrf -b $SDK_VER --depth 1
      - name: 🪁 Install nRF SDK
        run: |
          mkdir -p zephyr-workspace
          git clone https://github.com/nrfconnect/ncs-zigbee.git zephyr-workspace/ncs-zigbee -b $NCS_ZIGBEE_VER --depth 1
          sed -i "s/revision: v[0-9].[0-9].[0-9]/revision: ${SDK_VER}/g" zephyr-workspace/ncs-zigbee/west.yml
          # fixes missing type definition which causes error on SDK 3.x
          sed -i '/^config NRF_802154_CCA_ED_THRESHOLD$/a\	int "Energy detection threshold"' zephyr-workspace/ncs-zigbee/subsys/Kconfig

      - name: 🪁 Apply overlay
        run: |
          cp zephyr-workspace/extra/$BOARD_TARGET_NAME.overlay zephyr-workspace/ncs-zigbee/samples/ncp/boards/$BOARD_TARGET_NAME.overlay
          cp zephyr-workspace/extra/$BOARD_TARGET_NAME.conf zephyr-workspace/ncs-zigbee/samples/ncp/boards/$BOARD_TARGET_NAME.conf
          sed -i "s/current-speed = \<[0-9]+\>;/current-speed = <$BAUDRATE>;/" zephyr-workspace/ncs-zigbee/samples/ncp/boards/$BOARD_TARGET_NAME.overlay

          echo -e "\n\nzb_uint32_t zb_osif_get_fw_version(void) { return ${NCS_ZIGBEE_VER_HEX}; }" >> zephyr-workspace/ncs-zigbee/samples/ncp/src/main.c
          sed -i "s/net_pkt_set_txtime/net_pkt_set_timestamp_ns/" zephyr-workspace/ncs-zigbee/subsys/osif/zb_nrf_transceiver.c

      - name: ♻️ Initialize Zephyr Workspace
        # Set up the Zephyr workspace and install the Python dependencies
        run: |
          cd zephyr-workspace
          west init -l ncs-zigbee
          west update --narrow -o=--depth=1
          pip3 install -r zephyr/scripts/requirements.txt

      - name: 🔨 Build Project
        run: |
          cd zephyr-workspace
          west build ncs-zigbee/samples/ncp -b $BOARD_TARGET -Dmcuboot_EXTRA_CONF_FILE=$(pwd)/extra/mcuboot.conf
          mv build/merged.hex build/ncp-r23-$BOARD-$NCS_ZIGBEE_VER-$BAUDRATE.hex

      - name: Install adafruit-nrfutil
        run: >-
          pip install adafruit-nrfutil

      - name: 🔨 Build DFU package
        run: >-
          adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application zephyr-workspace/build/ncp-r23-$BOARD-$NCS_ZIGBEE_VER-$BAUDRATE.hex zephyr-workspace/build/ncp-r23-$BOARD-$NCS_ZIGBEE_VER-$BAUDRATE-dfu.zip

      - name: 📦 Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            zephyr-workspace/build/*.hex
            zephyr-workspace/build/*-dfu.zip
